/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnhLoiRouteImport } from './routes/anh-loi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DangKyDaiLyRouteImport } from './routes/dang-ky-dai-ly'
import { Route as CCategoryIdRouteImport } from './routes/c.$categoryId'
import { Route as CCategoryIdSeriesIdRouteImport } from './routes/c.$categoryId.$seriesId'
import { Route as CCategoryIdNNodeIdRouteImport } from './routes/c.$categoryId.n.$nodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnhLoiRoute = AnhLoiRouteImport.update({
  id: '/anh-loi',
  path: '/anh-loi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyDaiLyRoute = DangKyDaiLyRouteImport.update({
  id: '/dang-ky-dai-ly',
  path: '/dang-ky-dai-ly',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIdRoute = CCategoryIdRouteImport.update({
  id: '/c/$categoryId',
  path: '/c/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIdSeriesIdRoute = CCategoryIdSeriesIdRouteImport.update({
  id: '/$seriesId',
  path: '/$seriesId',
  getParentRoute: () => CCategoryIdRoute,
} as any)
const CCategoryIdNNodeIdRoute = CCategoryIdNNodeIdRouteImport.update({
  id: '/n/$nodeId',
  path: '/n/$nodeId',
  getParentRoute: () => CCategoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anh-loi': typeof AnhLoiRoute
  '/auth': typeof AuthRoute
  '/dang-ky-dai-ly': typeof DangKyDaiLyRoute
  '/c/$categoryId': typeof CCategoryIdRouteWithChildren
  '/c/$categoryId/$seriesId': typeof CCategoryIdSeriesIdRoute
  '/c/$categoryId/n/$nodeId': typeof CCategoryIdNNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anh-loi': typeof AnhLoiRoute
  '/auth': typeof AuthRoute
  '/dang-ky-dai-ly': typeof DangKyDaiLyRoute
  '/c/$categoryId': typeof CCategoryIdRouteWithChildren
  '/c/$categoryId/$seriesId': typeof CCategoryIdSeriesIdRoute
  '/c/$categoryId/n/$nodeId': typeof CCategoryIdNNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anh-loi': typeof AnhLoiRoute
  '/auth': typeof AuthRoute
  '/dang-ky-dai-ly': typeof DangKyDaiLyRoute
  '/c/$categoryId': typeof CCategoryIdRouteWithChildren
  '/c/$categoryId/$seriesId': typeof CCategoryIdSeriesIdRoute
  '/c/$categoryId/n/$nodeId': typeof CCategoryIdNNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anh-loi'
    | '/auth'
    | '/dang-ky-dai-ly'
    | '/c/$categoryId'
    | '/c/$categoryId/$seriesId'
    | '/c/$categoryId/n/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anh-loi'
    | '/auth'
    | '/dang-ky-dai-ly'
    | '/c/$categoryId'
    | '/c/$categoryId/$seriesId'
    | '/c/$categoryId/n/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/anh-loi'
    | '/auth'
    | '/dang-ky-dai-ly'
    | '/c/$categoryId'
    | '/c/$categoryId/$seriesId'
    | '/c/$categoryId/n/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnhLoiRoute: typeof AnhLoiRoute
  AuthRoute: typeof AuthRoute
  DangKyDaiLyRoute: typeof DangKyDaiLyRoute
  CCategoryIdRoute: typeof CCategoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anh-loi': {
      id: '/anh-loi'
      path: '/anh-loi'
      fullPath: '/anh-loi'
      preLoaderRoute: typeof AnhLoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky-dai-ly': {
      id: '/dang-ky-dai-ly'
      path: '/dang-ky-dai-ly'
      fullPath: '/dang-ky-dai-ly'
      preLoaderRoute: typeof DangKyDaiLyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$categoryId': {
      id: '/c/$categoryId'
      path: '/c/$categoryId'
      fullPath: '/c/$categoryId'
      preLoaderRoute: typeof CCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$categoryId/$seriesId': {
      id: '/c/$categoryId/$seriesId'
      path: '/$seriesId'
      fullPath: '/c/$categoryId/$seriesId'
      preLoaderRoute: typeof CCategoryIdSeriesIdRouteImport
      parentRoute: typeof CCategoryIdRoute
    }
    '/c/$categoryId/n/$nodeId': {
      id: '/c/$categoryId/n/$nodeId'
      path: '/n/$nodeId'
      fullPath: '/c/$categoryId/n/$nodeId'
      preLoaderRoute: typeof CCategoryIdNNodeIdRouteImport
      parentRoute: typeof CCategoryIdRoute
    }
  }
}

interface CCategoryIdRouteChildren {
  CCategoryIdSeriesIdRoute: typeof CCategoryIdSeriesIdRoute
  CCategoryIdNNodeIdRoute: typeof CCategoryIdNNodeIdRoute
}

const CCategoryIdRouteChildren: CCategoryIdRouteChildren = {
  CCategoryIdSeriesIdRoute: CCategoryIdSeriesIdRoute,
  CCategoryIdNNodeIdRoute: CCategoryIdNNodeIdRoute,
}

const CCategoryIdRouteWithChildren = CCategoryIdRoute._addFileChildren(
  CCategoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnhLoiRoute: AnhLoiRoute,
  AuthRoute: AuthRoute,
  DangKyDaiLyRoute: DangKyDaiLyRoute,
  CCategoryIdRoute: CCategoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
